## **The Cost of Achieving the 5 a Day Goal**

<center><img src="https://tse2.mm.bing.net/th?id=OIP.t3nmd_I60mh1C28tGAsS1gAAAA&pid=Api&P=0&h=220" style="width:500px;height:200px" align="center" />

## **Set up environment**

- A virtual enviroment was created from this project.
- Pip install was run 
- The necessary libraries were installed.

In [124]:

import pandas as pd

import matplotlib.pyplot as plt

#import requests

#from bs4 import BeautifulSoup

import os

## **Data Loading and Cleansing**

### **Data Loading and Cleansing - Part 1**

I will begin by loading, checking and making any needed edits to the below listed files.

- Fruits_Vegs_Colors.csv
- Fruit_Prices_2020.csv
- Fruit_Prices_2022.csv
- Vegetable_Prices_2020
- Vegetable_Prices_2022

#### Load Files

In [125]:
colors = pd.read_csv("Fruits_Vegs_Colors.csv")
fruits_20 = pd.read_csv("Fruit_Prices_2020.csv")
fruits_22 = pd.read_csv("Fruit_Prices_2022.csv")
vegetables_20 = pd.read_csv("Vegetable_Prices_2020.csv")
vegetables_22 = pd.read_csv("Vegetable_Prices_2020.csv")

#### View part of the data loaded by listing the first and last 5 records of each table

In [126]:
colors.head()

     Fruit_Veg Color
0       Apples   Red
1     Cherries   Red
2  Cranberries   Red
3       Grapes   Red
4  Pomegranate   Red

In [127]:
colors.tail()

         Fruit_Veg        Color
86         Raisins  Blue/Purple
87    Black olives  Blue/Purple
88  Purple Cabbage  Blue/Purple
89        eggplant  Blue/Purple
90   Black salsify  Blue/Purple

In [128]:
fruits_20.head()

,Fruit,Form,RetailPrice,RetailPriceUnit,Yield,CupEquivalentSize,CupEquivalentUnit,CupEquivalentPrice
0,Apples,Fresh,1.5193,per pound,0.90,0.2425,pounds,0.4094
1,"Apples, applesauce",Canned,1.0660,per pound,1.00,0.5401,pounds,0.5758
2,"Apples, ready-to-drink",Juice,0.7804,per pint,1.00,8.0000,fluid ounces,0.3902
3,"Apples, frozen concentrate",Juice,0.5853,per pint,1.00,8.0000,fluid ounces,0.2926
4,Apricots,Fresh,2.9665,per pound,0.93,0.3638,pounds,1.1603

In [129]:
fruits_20.tail()

,Fruit,Form,RetailPrice,RetailPriceUnit,Yield,CupEquivalentSize,CupEquivalentUnit,CupEquivalentPrice
57,Raspberries,Fresh,6.6391,per pound,0.96,0.3197,pounds,2.2107
58,Raspberries,Frozen,4.1877,per pound,1.00,0.3307,pounds,1.3849
59,Strawberries,Fresh,2.5800,per pound,0.94,0.3197,pounds,0.8774
60,Strawberries,Frozen,2.8189,per pound,1.00,0.3307,pounds,0.9322
61,Watermelon,Fresh,0.3604,per pound,0.52,0.3307,pounds,0.2292

In [130]:
fruits_22.head()

,Fruit,Form,RetailPrice,RetailPriceUnit,Yield,CupEquivalentSize,CupEquivalentUnit,CupEquivalentPrice
0,Apples,Fresh,1.8541,per pound,0.90,0.2425,pounds,0.4996
1,"Apples, applesauce",Canned,1.1705,per pound,1.00,0.5401,pounds,0.6323
2,"Apples, ready-to-drink",Juice,0.8699,per pint,1.00,8.0000,fluid ounces,0.4349
3,"Apples, frozen concentrate",Juice,0.6086,per pint,1.00,8.0000,fluid ounces,0.3043
4,Apricots,Fresh,3.6162,per pound,0.93,0.3638,pounds,1.4145

In [131]:
fruits_22.tail()

,Fruit,Form,RetailPrice,RetailPriceUnit,Yield,CupEquivalentSize,CupEquivalentUnit,CupEquivalentPrice
57,Raspberries,Fresh,7.7338,per pound,0.96,0.3197,pounds,2.5753
58,Raspberries,Frozen,6.1590,per pound,1.00,0.3307,pounds,2.0368
59,Strawberries,Fresh,2.9682,per pound,0.94,0.3197,pounds,1.0094
60,Strawberries,Frozen,3.3421,per pound,1.00,0.3307,pounds,1.1052
61,Watermelon,Fresh,0.3820,per pound,0.52,0.3307,pounds,0.2429

In [132]:
vegetables_20.head()

,Vegetable,Form,RetailPrice,RetailPriceUnit,Yield,CupEquivalentSize,CupEquivalentUnit,CupEquivalentPrice
0,Acorn squash,Fresh,1.1804,per pound,0.4586,0.4519,pounds,1.1633
1,Artichoke,Fresh,2.1913,per pound,0.3750,0.3858,pounds,2.2545
2,Artichoke,Canned,3.4119,per pound,0.6500,0.3858,pounds,2.0251
3,Asparagus,Fresh,2.7576,per pound,0.4938,0.3968,pounds,2.2159
4,Asparagus,Canned,3.1269,per pound,0.6500,0.3968,pounds,1.9090

In [133]:
vegetables_20.tail()

,Vegetable,Form,RetailPrice,RetailPriceUnit,Yield,CupEquivalentSize,CupEquivalentUnit,CupEquivalentPrice
88,Tomatoes,Canned,1.0175,per pound,1.0000,0.5401,pounds,0.5496
89,Turnip greens,Fresh,2.4176,per pound,0.7500,0.3197,pounds,1.0304
90,Turnip greens,Canned,1.0429,per pound,0.6500,0.3527,pounds,0.5660
91,Turnip greens,Frozen,1.9451,per pound,0.7760,0.3527,pounds,0.8841
92,Zucchini,Fresh,1.5489,per pound,0.7695,0.3968,pounds,0.7987

In [134]:
vegetables_22.head()

,Vegetable,Form,RetailPrice,RetailPriceUnit,Yield,CupEquivalentSize,CupEquivalentUnit,CupEquivalentPrice
0,Acorn squash,Fresh,1.1804,per pound,0.4586,0.4519,pounds,1.1633
1,Artichoke,Fresh,2.1913,per pound,0.3750,0.3858,pounds,2.2545
2,Artichoke,Canned,3.4119,per pound,0.6500,0.3858,pounds,2.0251
3,Asparagus,Fresh,2.7576,per pound,0.4938,0.3968,pounds,2.2159
4,Asparagus,Canned,3.1269,per pound,0.6500,0.3968,pounds,1.9090

#### Since I will concatenate the vegetables and fruits dataframes, I do the following:
- Verify that the columnn names are the same and have the same data type.
- Make any necessary adjustment.
- Add year column to each file

#### And the same token, since information from the color dataframe will be merge with the dataframe thatn contains the fruit and vegetables, I will do the following:
- Confirm that the joining fields have the same datatype
- Make any necesaary adjustment.

In [135]:
fruits_20.dtypes

Fruit                  object
Form                   object
RetailPrice           float64
RetailPriceUnit        object
Yield                 float64
CupEquivalentSize     float64
CupEquivalentUnit      object
CupEquivalentPrice    float64
dtype: object

In [136]:
fruits_22.dtypes

Fruit                  object
Form                   object
RetailPrice           float64
RetailPriceUnit        object
Yield                 float64
CupEquivalentSize     float64
CupEquivalentUnit      object
CupEquivalentPrice    float64
dtype: object

In [137]:
vegetables_20.dtypes

Vegetable              object
Form                   object
RetailPrice           float64
RetailPriceUnit        object
Yield                 float64
CupEquivalentSize     float64
CupEquivalentUnit      object
CupEquivalentPrice    float64
dtype: object

In [138]:
vegetables_22.dtypes

Vegetable              object
Form                   object
RetailPrice           float64
RetailPriceUnit        object
Yield                 float64
CupEquivalentSize     float64
CupEquivalentUnit      object
CupEquivalentPrice    float64
dtype: object

In [139]:
colors.dtypes

Fruit_Veg    object
Color        object
dtype: object

In [140]:
# Rename the Fruit columns in Fruits_20 and fruits_22  Produce.
fruits_20 = fruits_20.rename(columns={'Fruit' : 'Produce'})
fruits_22 = fruits_22.rename(columns={'Fruit' : 'Produce'})
vegetables_20 = vegetables_20.rename(columns={'Vegetable' : 'Produce'})
vegetables_22 = vegetables_22.rename(columns={'Vegetable' : 'Produce'})

#Add year field to 2020 and 2022 fruits and vegetables tables.df_produces
fruits_20['Year'] = 2020
fruits_22['Year'] = 2022
vegetables_20['Year'] = 2020
vegetables_22['Year'] = 2022

df_produces = pd.concat([fruits_20, fruits_22, vegetables_20, vegetables_22], axis=0).reset_index(drop=True)

#print the shape of the of the tables that were concatenated and the resulting tables, to validate result
fruits_20.shape, fruits_22.shape, vegetables_20.shape, vegetables_22.shape, df_produces.shape

((62, 9), (62, 9), (93, 9), (93, 9), (310, 9))

In [141]:
df_produces.head(10)

,Produce,Form,RetailPrice,RetailPriceUnit,Yield,CupEquivalentSize,CupEquivalentUnit,CupEquivalentPrice,Year
0,Apples,Fresh,1.5193,per pound,0.90,0.2425,pounds,0.4094,2020
1,"Apples, applesauce",Canned,1.0660,per pound,1.00,0.5401,pounds,0.5758,2020
2,"Apples, ready-to-drink",Juice,0.7804,per pint,1.00,8.0000,fluid ounces,0.3902,2020
3,"Apples, frozen concentrate",Juice,0.5853,per pint,1.00,8.0000,fluid ounces,0.2926,2020
4,Apricots,Fresh,2.9665,per pound,0.93,0.3638,pounds,1.1603,2020
5,"Apricots, packed in juice",Canned,1.6905,per pound,1.00,0.5401,pounds,0.9131,2020
6,"Apricots, packed in syrup or water",Canned,2.0600,per pound,0.65,0.4409,pounds,1.3974,2020
7,Apricots,Dried,6.6188,per pound,1.00,0.1433,pounds,0.9485,2020
8,Bananas,Fresh,0.5249,per pound,0.64,0.3307,pounds,0.2712,2020
9,"Berries, mixed",Frozen,3.5585,per pound,1.00,0.3307,pounds,1.1768,2020

In [142]:
df_produces.tail(10)

,Produce,Form,RetailPrice,RetailPriceUnit,Yield,CupEquivalentSize,CupEquivalentUnit,CupEquivalentPrice,Year
300,Spinach,Frozen,2.1330,per pound,0.7760,0.3748,pounds,1.0302,2022
301,Sweet potatoes,Fresh,1.1198,per pound,0.8818,0.4409,pounds,0.5599,2022
302,"Tomatoes, grape & cherry",Fresh,4.1458,per pound,0.9100,0.3748,pounds,1.7075,2022
303,"Tomatoes, roma & plum",Fresh,1.1618,per pound,0.9100,0.3748,pounds,0.4785,2022
304,"Tomatoes, large round",Fresh,2.3347,per pound,0.9100,0.3748,pounds,0.9616,2022
305,Tomatoes,Canned,1.0175,per pound,1.0000,0.5401,pounds,0.5496,2022
306,Turnip greens,Fresh,2.4176,per pound,0.7500,0.3197,pounds,1.0304,2022
307,Turnip greens,Canned,1.0429,per pound,0.6500,0.3527,pounds,0.5660,2022
308,Turnip greens,Frozen,1.9451,per pound,0.7760,0.3527,pounds,0.8841,2022
309,Zucchini,Fresh,1.5489,per pound,0.7695,0.3968,pounds,0.7987,2022

In [143]:
#### I will check for missing values in the Produce dataframe.
#### I will drop records with missing values in the produce_nm or CupEquivalentPrice columns, since they will be use later for joining and calculation.

In [144]:
#Check for null values
df_produces.isnull().sum()

Produce               0
Form                  0
RetailPrice           0
RetailPriceUnit       0
Yield                 0
CupEquivalentSize     0
CupEquivalentUnit     0
CupEquivalentPrice    0
Year                  0
dtype: int64

### **Data Loading and Cleansing - Part 2**

### Loading

Next, I will work on loading the 2016 data.

- The 2026 data is in single csv file per produce and have been saved to the folder Fruits_Vegs_2016.
- The name of the files are in following format: "<produce name> 2016.csv"; for example: "apples 2016.csv"
- Only the first 7 columns contain information. 
- Some files have additional columns with null values.

- An empty dataframe (df_produces_2016) will be created.
- For each file in the Fruits_Vegs_2016 folder, the following will be done:
    - Get the filename.
    - Extract the produce name from the file name.
    - Read the file into a dataframe.
    - If the dataframe have more than 7 columns, additional columns will be dropped.
    - The columns will be renamed to be consistent with the naming of the columns in df_produces (containing 2020 and 2022 data)
    - A column with the produce name will be added to the dataframe.
    - Concatenate the dataframe to dataframe df_produces_2026

### The following a sample 2026 file.

<img src="2016_sample_file.png" />

In [145]:
# Assign directory
directory = r"Fruits_Vegs_2016\\" 
df_produces_2016  = pd.DataFrame()

# Iterate over files in directory
for fname in os.listdir(directory):
    pos = fname.find(" ")
    produce_nm = fname[:pos]
    complete_filename = directory + fname
    df_produce = pd.read_csv(complete_filename, encoding='ISO-8859-1')

    #Information in these files are stored in the first 7 columns. The following drops any additional column.
    column_cnt = df_produce.shape[1]
    if column_cnt > 7:
        df_produce = df_produce.drop(df_produce.iloc[:,7:column_cnt], axis=1)   
    
    #The first row contains a description of the file, wwhich is read as the first column heading and the others are unnamed.
    #Therefore, the columns are renamed to be consistent with the columns in the dataframe with the 20202 and 2022 data.
   
    df_produce = df_produce.set_axis(['Form', 'RetailPrice', 'RetailPriceUnit', 'Yield', 'CupEquivalentSize', 'CupEquivalentUnit', 'CupEquivalentPrice'], axis=1)
    #df_produce['Produce'] = produce_nm
    df_produce.insert(0, "Produce", produce_nm)
    df_produces_2016 = pd.concat([df_produces_2016,df_produce])


 
df_produces_2016.head(10)

,Produce,Form,RetailPrice,RetailPriceUnit,Yield,CupEquivalentSize,CupEquivalentUnit,CupEquivalentPrice
0,acorn_squash,Form,Average retail price,NaN,Preparation,Size of a,NaN,Average price
1,acorn_squash,NaN,NaN,NaN,yield factor,cup equivalent,NaN,per cup equivalent
2,acorn_squash,Fresh1,$1.12,per pound,0.459,0.452,pounds,$1.10
3,acorn_squash,1It is assumed that consumers bake acorn squas...,NaN,NaN,NaN,NaN,NaN,NaN
4,acorn_squash,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,acorn_squash,"Source: Calculated by USDA, Economic Research ...",NaN,NaN,NaN,NaN,NaN,NaN
0,apples,Form,Average retail price,NaN,Preparation,Size of a,NaN,Average price
1,apples,NaN,NaN,NaN,yield factor,cup equivalent,NaN,per cup equivalent
2,apples,Fresh1,$1.62,per pound,0.9,0.243,pounds,$0.44
3,apples,Applesauce2,$1.05,per pound,1,0.540,pounds,$0.57

### Cleansing

Now that the 2016 files are loaded, I will work on cleansing the data to align with the 2020 and 2022 data.

In [146]:
# Now, I am going to drop rows that do not containd the data needed for the analysis: 
#   Rows were the RetailPriceUnit field is null, based on the records displayed above. 
df_produces_2016.dropna(subset=['RetailPriceUnit'], inplace=True) 
df_produces_2016.head(10)

,Produce,Form,RetailPrice,RetailPriceUnit,Yield,CupEquivalentSize,CupEquivalentUnit,CupEquivalentPrice
2,acorn_squash,Fresh1,$1.12,per pound,0.459,0.452,pounds,$1.10
2,apples,Fresh1,$1.62,per pound,0.9,0.243,pounds,$0.44
3,apples,Applesauce2,$1.05,per pound,1,0.540,pounds,$0.57
5,apples,Ready to drink3,$0.63,per pint,1,8,fl oz,$0.32
6,apples,Frozen4,$0.51,per pint,1,8,fl oz,$0.26
2,apricots,Fresh1,$3.09,per pound,0.93,0.364,pounds,$1.21
4,apricots,Packed in juice2,$1.47,per pound,1,0.540,pounds,$0.80
5,apricots,"Packed in syrup, syrup discarded3",$1.86,per pound,0.65,0.441,pounds,$1.26
6,apricots,Dried4,$7.33,per pound,1,0.143,pounds,$1.05
2,artichoke,Fresh1,$2.36,per pound,0.375,0.386,pounds,$2.43

Let's compare the stucture of the the dataframe with the 2016 data against dataframe with the 2020 and 2022 and make any necessary change.

In [147]:
df_produces.dtypes

Produce                object
Form                   object
RetailPrice           float64
RetailPriceUnit        object
Yield                 float64
CupEquivalentSize     float64
CupEquivalentUnit      object
CupEquivalentPrice    float64
Year                    int64
dtype: object

In [148]:
df_produces_2016.dtypes

Produce               object
Form                  object
RetailPrice           object
RetailPriceUnit       object
Yield                 object
CupEquivalentSize     object
CupEquivalentUnit     object
CupEquivalentPrice    object
dtype: object

In [149]:
# Change the type of the column that do not match
df_produces_2016['RetailPrice'] = df_produces_2016['RetailPrice'].str.replace('$', '').astype(float)
df_produces_2016['Yield'] = df_produces_2016['Yield'].str.replace(',', '').astype(float)
df_produces_2016['CupEquivalentSize'] = df_produces_2016['CupEquivalentSize'].str.replace('$', '').astype(float)
df_produces_2016['CupEquivalentPrice'] = df_produces_2016['CupEquivalentPrice'].str.replace('$', '').astype(float)

#Add year field to the 2016 data
df_produces_2016['Year'] = 2016

In [150]:
df_produces.dtypes

Produce                object
Form                   object
RetailPrice           float64
RetailPriceUnit        object
Yield                 float64
CupEquivalentSize     float64
CupEquivalentUnit      object
CupEquivalentPrice    float64
Year                    int64
dtype: object

In [151]:
df_produces_2016.dtypes

Produce                object
Form                   object
RetailPrice           float64
RetailPriceUnit        object
Yield                 float64
CupEquivalentSize     float64
CupEquivalentUnit      object
CupEquivalentPrice    float64
Year                    int64
dtype: object

Now that the dataframes structure are aligned. Let's compare the data in the 'Form' column, which will be part of the analysis.

In [152]:
df_produces.value_counts('Form')

Form
Fresh     132
Canned     72
Frozen     50
Dried      34
Juice      22
Name: count, dtype: int64

In [153]:
#Get distict values in Form column and clean
df_produces_2016.value_counts('Form')

Form
Fresh1                                 44
Frozen2                                11
Canned1                                10
Frozen3                                 9
Canned2                                 8
Dried2                                  8
  Packed in juice2                      4
Frozen4                                 3
  Packed in syrup or water3             3
Dried1                                  3
Canned3                                 2
  Canned1                               2
Ready to drink3                         2
Juice, ready to drink2                  2
Dried4                                  2
  Packed in juice1                      1
  Full Heads                            1
  Packed in syrup, syrup discarded3     1
  Packed in syrup or water2             1
Canned1,2                               1
  Hearts                                1
  Heads1                                1
  Heads                                 1
  Frozen4                               1
  Frozen2                               1
  Florets1                              1
  Florets                               1
Dried1                                  1
Dried (Prunes)2                         1
Canned5                                 1
Cooked whole1                           1
Applesauce2                             1
Boiled                                  1
Canned, packed in syrup or water2       1
Fresh red cabbage1                      1
Fresh1                                  1
Fresh, peeled1                          1
Fresh, consumed with peel1              1
Frozen                                  1
Frozen1                                 1
Frozen french fries2                    1
Fresh green cabbage1                    1
Dried3                                  1
Grape and cherry1,2                     1
Frozen6                                 1
Large round1,4                          1
Juice, ready to drink3                  1
Raw                                     1
Raw baby2                               1
Raw whole1                              1
Raisins2                                1
Ready to drink2                         1
Ready to drink5                         1
Roma and plum1,3                        1
Sauerkraut2                             1
Sliced                                  1
Sticks                                  1
Trimmed bunches                         1
Whole                                   1
Name: count, dtype: int64

After seeing the vast differences in the values in the Form columns, I decided to dump the content of df_produces_2016 and visually compared to the 2020 files. Based on the comparison, I decided that the following edits were needed to align the 2016 data to the 2020 & 2022 data.

In [154]:
# Clean-up values in column Produce and Form to align with values in df_produces
df_produces_2016['Produce'] = df_produces_2016['Produce'].str.capitalize()
df_produces_2016['Produce'] = df_produces_2016['Produce'].str.replace("_", " ")
df_produces_2016['Form'] = df_produces_2016['Form'].str.strip()
df_produces_2016['Form'] = df_produces_2016['Form'].str.replace("1,2", "")
df_produces_2016['Form'] = df_produces_2016['Form'].str.replace("1,3", "")
df_produces_2016['Form'] = df_produces_2016['Form'].str.replace("1,4", "")
df_produces_2016['Form'] = df_produces_2016['Form'].str.replace("1", "")
df_produces_2016['Form'] = df_produces_2016['Form'].str.replace("2", "")
df_produces_2016['Form'] = df_produces_2016['Form'].str.replace("3", "")
df_produces_2016['Form'] = df_produces_2016['Form'].str.replace("4", "")
df_produces_2016['Form'] = df_produces_2016['Form'].str.replace("5", "")
df_produces_2016['Form'] = df_produces_2016['Form'].str.replace("6", "")
df_produces_2016['Form'] = df_produces_2016['Form'].str.replace("3", "")
df_produces_2016['Form'] = df_produces_2016['Form'].str.replace("4", "")
df_produces_2016['Form'] = df_produces_2016['Form'].str.replace("5", "")
df_produces_2016['Form'] = df_produces_2016['Form'].str.replace("6", "")
df_produces_2016.loc[df_produces_2016['Form'] == 'Applesauce', ['Produce', 'Form']] = ['Apples, applesauce', 'Canned']
df_produces_2016.loc[(df_produces_2016['Form'] == 'Canned, packed in syrup or water')  & (df_produces_2016['Produce'] =='Cherries'),  ['Produce', 'Form']] = ['Cherries, packed in syrup or water', 'Canned']
df_produces_2016.loc[(df_produces_2016['Form'] == 'Packed in juice')  & (df_produces_2016['Produce'] =='Fruit cocktail'),  ['Produce', 'Form']] = ['Fruit cocktail, packed in juice', 'Canned']
df_produces_2016.loc[(df_produces_2016['Form'] == 'Packed in juice')  & (df_produces_2016['Produce'] =='Peaches'),  ['Produce', 'Form']] = ['Peaches, packed in juice', 'Canned']
df_produces_2016.loc[(df_produces_2016['Form'] == 'Packed in juice')  & (df_produces_2016['Produce'] =='Pears'),  ['Produce', 'Form']] = ['Pears, packed in juice', 'Canned']
df_produces_2016.loc[(df_produces_2016['Form'] == 'Packed in juice')  & (df_produces_2016['Produce'] =='Pineapple'),  ['Produce', 'Form']] = ['Pineapple, packed in juice', 'Canned']
df_produces_2016.loc[(df_produces_2016['Form'] == 'Packed in syrup or water')  & (df_produces_2016['Produce'] =='Fruit cocktail'),  ['Produce', 'Form']] = ['Fruit cocktail, packed in syrup or water', 'Canned']
df_produces_2016.loc[(df_produces_2016['Form'] == 'Packed in syrup or water')  & (df_produces_2016['Produce'] =='Peaches'),  ['Produce', 'Form']] = ['Peaches, packed in syrup or water', 'Canned']
df_produces_2016.loc[(df_produces_2016['Form'] == 'Packed in syrup or water')  & (df_produces_2016['Produce'] =='Pears'),  ['Produce', 'Form']] = ['Pears, packed in syrup or water', 'Canned']
df_produces_2016.loc[(df_produces_2016['Form'] == 'Packed in syrup or water')  & (df_produces_2016['Produce'] =='Pineapple'),  ['Produce', 'Form']] = ['Pineapple, packed in syrup or water', 'Canned']
df_produces_2016.loc[(df_produces_2016['Form'] == 'Packed in syrup, syrup discarded')  & (df_produces_2016['Produce'] =='Apricots'),  ['Produce', 'Form']] = ['Apricots, Packed in syrup',  'Canned']
df_produces_2016.loc[(df_produces_2016['Form'] == 'Florets') & (df_produces_2016['Produce'] == 'Broccoli'),  ['Produce', 'Form']] = ['Broccoli florets', 'Fresh']
df_produces_2016.loc[(df_produces_2016['Form'] == 'Florets') & (df_produces_2016['Produce'] == 'Cauliflower'),  ['Produce', 'Form']] = ['Cauliflower florets', 'Fresh']
df_produces_2016.loc[(df_produces_2016['Form'] == 'Frozen')  & (df_produces_2016['Produce'] =='Apples'),  ['Produce', 'Form']] = ['Apples, frozen concentrate', 'Juice']
df_produces_2016.loc[(df_produces_2016['Form'] == 'Frozen')  & (df_produces_2016['Produce'] =='Grapes'),    ['Produce', 'Form']] = ['Grapes, frozen concentrate', 'Juice']
df_produces_2016.loc[(df_produces_2016['Form'] == 'Frozen')  & (df_produces_2016['Produce'] =='Oranges'),    ['Produce', 'Form']] = ['Oranges, frozen concentrate', 'Juice']
df_produces_2016.loc[(df_produces_2016['Form'] == 'Frozen')  & (df_produces_2016['Produce'] =='Pineapples'),    ['Produce', 'Form']] = ['Pineapples, frozen concentrate', 'Juice']
df_produces_2016.loc[(df_produces_2016['Form'] == 'Heads') & (df_produces_2016['Produce']== 'Broccoli'),  ['Produce', 'Form']] = ['Broccoli heads', 'Fresh']
df_produces_2016.loc[(df_produces_2016['Form'] == 'Heads') & (df_produces_2016['Produce']== 'Cauliflower'),  ['Produce', 'Form']] = ['Cauliflower heads', 'Fresh']
df_produces_2016.loc[(df_produces_2016['Form'] == 'Juice, ready to drink')  & (df_produces_2016['Produce'] =='Grapefruit'),    ['Produce', 'Form']] = ['Grapefruit, ready to drink', 'Juice']
df_produces_2016.loc[(df_produces_2016['Form'] == 'Juice, ready to drink')  & (df_produces_2016['Produce'] =='Plums'),    ['Produce', 'Form']] = ['Plums (oprunes), ready to drink', 'Juice']
df_produces_2016.loc[(df_produces_2016['Form'] == 'Juice, ready to drink')  & (df_produces_2016['Produce'] =='Pomegranate'),    ['Produce', 'Form']] = ['Pomegranate, ready to drink', 'Juice']
df_produces_2016.loc[(df_produces_2016['Form'] == 'Ready to drink')  & (df_produces_2016['Produce'] =='Apples'),    ['Produce', 'Form']] = ['Apples, ready to drink', 'Juice']
df_produces_2016.loc[(df_produces_2016['Form'] == 'Ready to drink')  & (df_produces_2016['Produce'] =='Grapes'),    ['Produce', 'Form']] = ['Grapes, ready to drink', 'Juice']
df_produces_2016.loc[(df_produces_2016['Form'] == 'Ready to drink')  & (df_produces_2016['Produce'] =='Oranges'),    ['Produce', 'Form']] = ['Oranges, ready to drink', 'Juice']
df_produces_2016.loc[(df_produces_2016['Form'] == 'Ready to drink')  & (df_produces_2016['Produce'] =='Pineapple'),    ['Produce', 'Form']] = ['Pineapple, ready to drink', 'Juice']
df_produces_2016.loc[df_produces_2016['Form'] == 'Cooked whole',  ['Produce', 'Form']] = ['Carrots, cooked whole', 'Fresh']
df_produces_2016.loc[df_produces_2016['Form'] == 'Dried (Prunes)',  ['Produce', 'Form']] = ['Plums (prunes)',  'Dried']
df_produces_2016.loc[df_produces_2016['Form'] == 'Fresh green cabbage',  ['Produce', 'Form']] = ['Cabbage, green', 'Fresh']
df_produces_2016.loc[df_produces_2016['Form'] == 'Fresh red cabbage',  ['Produce', 'Form']] = ['Cabbage, red', 'Fresh']
df_produces_2016.loc[df_produces_2016['Form'] == 'Fresh, consumed with peel',  ['Produce', 'Form']] = ['Cucumber with peel',  'Fresh']
df_produces_2016.loc[df_produces_2016['Form'] == 'Fresh, peeled' ,  ['Produce', 'Form']] = ['Cucumber without peel',  'Fresh']
df_produces_2016.loc[df_produces_2016['Form'] == 'Frozen french fries',  ['Produce', 'Form']] = ['Potatoes, french fries',  'Frozen']
df_produces_2016.loc[df_produces_2016['Form'] == 'Full Heads',  ['Produce', 'Form']] = ['Lettuce, romaine, heads',  'Fresh']
df_produces_2016.loc[df_produces_2016['Form'] == 'Grape and cherry',  ['Produce', 'Form']] = ['Tomatoes, grape and cherry',  'Fresh']
df_produces_2016.loc[df_produces_2016['Form'] == 'Hearts',  ['Produce', 'Form']] = ['Lettuce, romaine, hearts',  'Fresh']
df_produces_2016.loc[df_produces_2016['Form'] == 'Large round',  ['Produce', 'Form']] = ['Tomatoes, Large round',  'Fresh']
df_produces_2016.loc[(df_produces_2016['Form'] == 'Packed in juice')  & (df_produces_2016['Produce'] =='Apricots'),  ['Produce', 'Form']] = ['Apricots, Packed in juice',  'Canned']
df_produces_2016.loc[df_produces_2016['Form'] == 'Raw baby',  ['Produce', 'Form']] = ['Carrots, raw baby', 'Fresh']
df_produces_2016.loc[df_produces_2016['Form'] == 'Raw whole',  ['Produce', 'Form']] = ['Carrots, raw whole', 'Fresh']
df_produces_2016.loc[df_produces_2016['Form'] == 'Roma and plum',  ['Produce', 'Form']] = ['Tomatoes, roma and plum',  'Fresh']
df_produces_2016.loc[df_produces_2016['Form'] == 'Sauerkraut',  ['Produce', 'Form']] = ['Cabbage, sauerkraut', 'Canned']
df_produces_2016.loc[df_produces_2016['Form'] == 'Sliced',  ['Produce', 'Form']] = ['Mushrooms, sliced',  'Fresh']
df_produces_2016.loc[df_produces_2016['Form'] == 'Sticks',  ['Produce', 'Form']] = ['Celerty sticks', 'Fresh']
df_produces_2016.loc[df_produces_2016['Form'] == 'Trimmed bunches',  ['Produce', 'Form']] = ['Celery, trimmed bunches', 'Fresh']
df_produces_2016.loc[df_produces_2016['Form'] == 'Whole',  ['Produce', 'Form']] = ['Mushrooms, whole',  'Fresh']
df_produces_2016.loc[df_produces_2016['Form'] == 'Raisins',  ['Produce', 'Form']] = ['Grapes (raisins)',  'Dried']
df_produces_2016.loc[(df_produces_2016['Form'] == 'Boiled')  & (df_produces_2016['Produce'] =='Spinach'),  ['Produce', 'Form']] = ['Spinach, boiled',  'Fresh']
df_produces_2016.loc[(df_produces_2016['Form'] == 'Raw')  & (df_produces_2016['Produce'] =='Spinach'),  ['Produce', 'Form']] = ['Spinach, eaten raw',  'Fresh']

df_produces_2016.value_counts('Form')

Form
Fresh     67
Canned    37
Frozen    26
Dried     17
Juice     10
Name: count, dtype: int64

In [155]:
df_produces_2016.head()

,Produce,Form,RetailPrice,RetailPriceUnit,Yield,CupEquivalentSize,CupEquivalentUnit,CupEquivalentPrice,Year
2,Acorn squash,Fresh,1.12,per pound,0.459,0.452,pounds,1.10,2016
2,Apples,Fresh,1.62,per pound,0.900,0.243,pounds,0.44,2016
3,"Apples, applesauce",Canned,1.05,per pound,1.000,0.540,pounds,0.57,2016
5,"Apples, ready to drink",Juice,0.63,per pint,1.000,8.000,fl oz,0.32,2016
6,"Apples, frozen concentrate",Juice,0.51,per pint,1.000,8.000,fl oz,0.26,2016

In [156]:


df_produces.value_counts('Form')

Form
Fresh     132
Canned     72
Frozen     50
Dried      34
Juice      22
Name: count, dtype: int64

Now that the 2016 data is clean, I will add to the produces dataframe.

In [169]:
df_produces = pd.concat([fruits_20, fruits_22, vegetables_20, vegetables_22, df_produces_2016], axis=0).reset_index(drop=True)
df_produces.head(10)

,Produce,Form,RetailPrice,RetailPriceUnit,Yield,CupEquivalentSize,CupEquivalentUnit,CupEquivalentPrice,Year
0,Apples,Fresh,1.5193,per pound,0.90,0.2425,pounds,0.4094,2020
1,"Apples, applesauce",Canned,1.0660,per pound,1.00,0.5401,pounds,0.5758,2020
2,"Apples, ready-to-drink",Juice,0.7804,per pint,1.00,8.0000,fluid ounces,0.3902,2020
3,"Apples, frozen concentrate",Juice,0.5853,per pint,1.00,8.0000,fluid ounces,0.2926,2020
4,Apricots,Fresh,2.9665,per pound,0.93,0.3638,pounds,1.1603,2020
5,"Apricots, packed in juice",Canned,1.6905,per pound,1.00,0.5401,pounds,0.9131,2020
6,"Apricots, packed in syrup or water",Canned,2.0600,per pound,0.65,0.4409,pounds,1.3974,2020
7,Apricots,Dried,6.6188,per pound,1.00,0.1433,pounds,0.9485,2020
8,Bananas,Fresh,0.5249,per pound,0.64,0.3307,pounds,0.2712,2020
9,"Berries, mixed",Frozen,3.5585,per pound,1.00,0.3307,pounds,1.1768,2020

In [170]:
df_produces.tail(10)

,Produce,Form,RetailPrice,RetailPriceUnit,Yield,CupEquivalentSize,CupEquivalentUnit,CupEquivalentPrice,Year
457,Sweet potatoes,Fresh,1.05,per pound,0.811,0.441,pounds,0.57,2016
458,Tangerines,Fresh,1.48,per pound,0.740,0.408,pounds,0.82,2016
459,"Tomatoes, grape and cherry",Fresh,3.48,per pound,0.910,0.375,pounds,1.43,2016
460,"Tomatoes, roma and plum",Fresh,1.29,per pound,0.910,0.375,pounds,0.53,2016
461,"Tomatoes, Large round",Fresh,2.01,per pound,0.910,0.375,pounds,0.83,2016
462,Tomatoes,Canned,0.91,per pound,1.000,0.540,pounds,0.49,2016
463,Turnip greens,Fresh,2.51,per pound,0.750,0.320,pounds,1.07,2016
464,Turnip greens,Canned,0.78,per pound,0.650,0.353,pounds,0.43,2016
465,Turnip greens,Frozen,1.58,per pound,0.776,0.353,pounds,0.72,2016
466,Watermelon,Fresh,0.32,per pound,0.520,0.331,pounds,0.20,2016

In [171]:
df_produces.isnull().sum()

Produce               0
Form                  0
RetailPrice           0
RetailPriceUnit       0
Yield                 0
CupEquivalentSize     0
CupEquivalentUnit     0
CupEquivalentPrice    0
Year                  0
dtype: int64

In [159]:
fruits_22.tail()

,Produce,Form,RetailPrice,RetailPriceUnit,Yield,CupEquivalentSize,CupEquivalentUnit,CupEquivalentPrice,Year
57,Raspberries,Fresh,7.7338,per pound,0.96,0.3197,pounds,2.5753,2022
58,Raspberries,Frozen,6.1590,per pound,1.00,0.3307,pounds,2.0368,2022
59,Strawberries,Fresh,2.9682,per pound,0.94,0.3197,pounds,1.0094,2022
60,Strawberries,Frozen,3.3421,per pound,1.00,0.3307,pounds,1.1052,2022
61,Watermelon,Fresh,0.3820,per pound,0.52,0.3307,pounds,0.2429,2022

In [160]:
#url = "https://fruitsandveggies.org/stories/fruit-and-veggie-color-list"
url = 'https://www.heart.org/en/healthy-living/healthy-eating/add-color/eat-more-color'
response = requests.get(url)
response

NameError: name 'requests' is not defined