In [47]:

import pandas as pd

import matplotlib.pyplot as plt

import requests

from bs4 import BeautifulSoup

import os

In [48]:
colors = pd.read_csv("Fruits_Vegs_Colors.csv")
colors.head()

     Fruit_Veg Color
0       Apples   Red
1     Cherries   Red
2  Cranberries   Red
3       Grapes   Red
4  Pomegranate   Red

In [49]:
fruits_20 = pd.read_csv("Fruit_Prices_2020.csv")
fruits_20.head()

,Fruit,Form,RetailPrice,RetailPriceUnit,Yield,CupEquivalentSize,CupEquivalentUnit,CupEquivalentPrice
0,Apples,Fresh,1.5193,per pound,0.90,0.2425,pounds,0.4094
1,"Apples, applesauce",Canned,1.0660,per pound,1.00,0.5401,pounds,0.5758
2,"Apples, ready-to-drink",Juice,0.7804,per pint,1.00,8.0000,fluid ounces,0.3902
3,"Apples, frozen concentrate",Juice,0.5853,per pint,1.00,8.0000,fluid ounces,0.2926
4,Apricots,Fresh,2.9665,per pound,0.93,0.3638,pounds,1.1603

In [50]:
fruits_22 = pd.read_csv("Fruit_Prices_2022.csv")
fruits_22.head()

,Fruit,Form,RetailPrice,RetailPriceUnit,Yield,CupEquivalentSize,CupEquivalentUnit,CupEquivalentPrice
0,Apples,Fresh,1.8541,per pound,0.90,0.2425,pounds,0.4996
1,"Apples, applesauce",Canned,1.1705,per pound,1.00,0.5401,pounds,0.6323
2,"Apples, ready-to-drink",Juice,0.8699,per pint,1.00,8.0000,fluid ounces,0.4349
3,"Apples, frozen concentrate",Juice,0.6086,per pint,1.00,8.0000,fluid ounces,0.3043
4,Apricots,Fresh,3.6162,per pound,0.93,0.3638,pounds,1.4145

In [51]:
vegetables_20 = pd.read_csv("Vegetable_Prices_2020.csv")
vegetables_20.head()

,Vegetable,Form,RetailPrice,RetailPriceUnit,Yield,CupEquivalentSize,CupEquivalentUnit,CupEquivalentPrice
0,Acorn squash,Fresh,1.1804,per pound,0.4586,0.4519,pounds,1.1633
1,Artichoke,Fresh,2.1913,per pound,0.3750,0.3858,pounds,2.2545
2,Artichoke,Canned,3.4119,per pound,0.6500,0.3858,pounds,2.0251
3,Asparagus,Fresh,2.7576,per pound,0.4938,0.3968,pounds,2.2159
4,Asparagus,Canned,3.1269,per pound,0.6500,0.3968,pounds,1.9090

In [52]:
vegetables_22 = pd.read_csv("Vegetable_Prices_2022.csv")
vegetables_22.head()

,Vegetable,Form,RetailPrice,RetailPriceUnit,Yield,CupEquivalentSize,CupEquivalentUnit,CupEquivalentPrice
0,Acorn squash,Fresh,1.2136,per pound,0.4586,0.4519,pounds,1.1961
1,Artichoke,Fresh,2.4703,per pound,0.3750,0.3858,pounds,2.5415
2,Artichoke,Canned,3.4498,per pound,0.6500,0.3858,pounds,2.0476
3,Asparagus,Fresh,2.9531,per pound,0.4938,0.3968,pounds,2.3731
4,Asparagus,Canned,3.4328,per pound,0.6500,0.3968,pounds,2.0958

In [87]:
# Assign directory
directory = r"Fruits_Vegs_2016\\" 
df_produces_2016  = pd.DataFrame()

# Iterate over files in directory
for fname in os.listdir(directory):
    pos = fname.find(" ")
    produce_nm = fname[:pos]
    complete_filename = directory + fname
    df_produce = pd.read_csv(complete_filename, encoding='ISO-8859-1')

    #Information in these files are stored in the first 8 columns. The following drops any additional column.
    column_cnt = df_produce.shape[1]
    if column_cnt > 7:
        df_produce = df_produce.drop(df_produce.iloc[:,7:column_cnt], axis=1)   
    
    #The first row contains a description of the file, wwhich is read as the first column heading and the others are unnamed.
    #Therefore, the columns are renamed to be consistent with the columns in the files for 20202 and 2022
    #This also enable merging them into a single dataframe
    df_produce = df_produce.set_axis(['Form', 'RetailPrice', 'RetailPriceUnit', 'Yield', 'CupEquivalentSize', 'CupEquivalentUnit', 'CupEquivalentPrice'], axis=1)
    df_produce['produce_name'] = produce_nm
    df_produces_2016 = pd.concat([df_produces_2016,df_produce])


 
df_produces_2016.head(10)

,Form,RetailPrice,RetailPriceUnit,Yield,CupEquivalentSize,CupEquivalentUnit,CupEquivalentPrice,produce_name
0,Form,Average retail price,NaN,Preparation,Size of a,NaN,Average price,acorn_squash
1,NaN,NaN,NaN,yield factor,cup equivalent,NaN,per cup equivalent,acorn_squash
2,Fresh1,$1.12,per pound,0.459,0.452,pounds,$1.10,acorn_squash
3,1It is assumed that consumers bake acorn squas...,NaN,NaN,NaN,NaN,NaN,NaN,acorn_squash
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,acorn_squash
5,"Source: Calculated by USDA, Economic Research ...",NaN,NaN,NaN,NaN,NaN,NaN,acorn_squash
0,Form,Average retail price,NaN,Preparation,Size of a,NaN,Average price,apples
1,NaN,NaN,NaN,yield factor,cup equivalent,NaN,per cup equivalent,apples
2,Fresh1,$1.62,per pound,0.9,0.243,pounds,$0.44,apples
3,Applesauce2,$1.05,per pound,1,0.540,pounds,$0.57,apples

In [88]:
# Now, I am going to drop rows that do not containd the data needed for the analysis: 
#   Rows were the RetailPriceUnit field is null 
df_produces_2016.dropna(subset=['RetailPriceUnit'], inplace=True)

In [84]:
df_produces_2016.head(8)

,Form,RetailPrice,RetailPriceUnit,Yield,CupEquivalentSize,CupEquivalentUnit,CupEquivalentPrice,produce_name
2,Fresh1,$1.12,per pound,0.459,0.452,pounds,$1.10,acorn_squash
2,Fresh1,$1.62,per pound,0.9,0.243,pounds,$0.44,apples
3,Applesauce2,$1.05,per pound,1,0.540,pounds,$0.57,apples
5,Ready to drink3,$0.63,per pint,1,8,fl oz,$0.32,apples
6,Frozen4,$0.51,per pint,1,8,fl oz,$0.26,apples
2,Fresh1,$3.09,per pound,0.93,0.364,pounds,$1.21,apricots
4,Packed in juice2,$1.47,per pound,1,0.540,pounds,$0.80,apricots
5,"Packed in syrup, syrup discarded3",$1.86,per pound,0.65,0.441,pounds,$1.26,apricots

In [90]:
#Get distict values in Form column and clean
df_produces_2016.value_counts('Form')

Form
Fresh1                                 44
Frozen2                                11
Canned1                                10
Frozen3                                 9
Canned2                                 8
Dried2                                  8
  Packed in juice2                      4
Frozen4                                 3
  Packed in syrup or water3             3
Dried1                                  3
Canned3                                 2
  Canned1                               2
Ready to drink3                         2
Juice, ready to drink2                  2
Dried4                                  2
  Packed in juice1                      1
  Full Heads                            1
  Packed in syrup, syrup discarded3     1
  Packed in syrup or water2             1
Canned1,2                               1
  Hearts                                1
  Heads1                                1
  Heads                                 1
  Frozen4                               1
  Frozen2                               1
  Florets1                              1
  Florets                               1
Dried1                                  1
Dried (Prunes)2                         1
Canned5                                 1
Cooked whole1                           1
Applesauce2                             1
Boiled                                  1
Canned, packed in syrup or water2       1
Fresh red cabbage1                      1
Fresh1                                  1
Fresh, peeled1                          1
Fresh, consumed with peel1              1
Frozen                                  1
Frozen1                                 1
Frozen french fries2                    1
Fresh green cabbage1                    1
Dried3                                  1
Grape and cherry1,2                     1
Frozen6                                 1
Large round1,4                          1
Juice, ready to drink3                  1
Raw                                     1
Raw baby2                               1
Raw whole1                              1
Raisins2                                1
Ready to drink2                         1
Ready to drink5                         1
Roma and plum1,3                        1
Sauerkraut2                             1
Sliced                                  1
Sticks                                  1
Trimmed bunches                         1
Whole                                   1
Name: count, dtype: int64

In [ ]:
# Change the Form column to a string and clean-up values
#df_produces_2016['Form'] = df_produces_2016['Form'].astype('string')
#df_produces_2016['Form'] = df_produces_2016['Form'].strip()

In [94]:
# Clean-up values in column Form

df_produces_2016 = df_produces_2016.Form.replace("1,2", "")

AttributeError: 'Series' object has no attribute 'Form'

In [ ]:

df_produces_2016 = df_produces_2016.Form.replace("1,3", "")
df_produces_2016 = df_produces_2016.Form.replace("1,4", "")
df_produces_2016 = df_produces_2016.Form.replace("1", "")
df_produces_2016 = df_produces_2016.Form.replace("2", "")
df_produces_2016 = df_produces_2016.Form.replace("3", "")
df_produces_2016 = df_produces_2016.Form.replace("4", "")
df_produces_2016 = df_produces_2016.Form.replace("5", "")
df_produces_2016 = df_produces_2016.Form.replace("6", "")

AttributeError: 'Series' object has no attribute 'Form'

In [ ]:
# Change the Form column to a string and clean-up values
df_produces_2016['Form'] = df_produces_2016['Form'].astype('string')
df_produces_2016['Form'] = df_produces_2016['Form'].strip()

AttributeError: 'Series' object has no attribute 'strip'

In [ ]:

df_produces_2016['Form'] = df['City'].replace('New York', 'San Francisco')

In [ ]:
#url = "https://fruitsandveggies.org/stories/fruit-and-veggie-color-list"
url = 'https://www.heart.org/en/healthy-living/healthy-eating/add-color/eat-more-color'
response = requests.get(url)
response